// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
// Options used:
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod houetor {
        pub mod calc {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod calc {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_add_cabi<T_: Guest>(arg0: f64, arg1: f64) -> f64 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = { T_::add(arg0, arg1) };
                        _rt::as_f64(result0)
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_fibonacci_cabi<T_: Guest>(arg0: i32) -> i64 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = { T_::fibonacci(arg0 as u32) };
                        _rt::as_i64(result0)
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_greet_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result1 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(
                                arg0.cast(),
                                len0,
                                len0,
                            );
                            T_::greet(_rt::string_lift(bytes0))
                        };
                        let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                        let vec3 = (result1.into_bytes()).into_boxed_slice();
                        let ptr3 = vec3.as_ptr().cast::<u8>();
                        let len3 = vec3.len();
                        ::core::mem::forget(vec3);
                        *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                        *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                        ptr2
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_greet<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = *arg0.add(0).cast::<*mut u8>();
                        let l1 = *arg0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l0, l1, 1);
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_read_file_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result1 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(
                                arg0.cast(),
                                len0,
                                len0,
                            );
                            T_::read_file(_rt::string_lift(bytes0))
                        };
                        let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result1 {
                            Ok(e) => {
                                *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                                let vec3 = (e.into_bytes()).into_boxed_slice();
                                let ptr3 = vec3.as_ptr().cast::<u8>();
                                let len3 = vec3.len();
                                ::core::mem::forget(vec3);
                                *ptr2
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len3;
                                *ptr2
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr3.cast_mut();
                            }
                            Err(e) => {
                                *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                                let vec4 = (e.into_bytes()).into_boxed_slice();
                                let ptr4 = vec4.as_ptr().cast::<u8>();
                                let len4 = vec4.len();
                                ::core::mem::forget(vec4);
                                *ptr2
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len4;
                                *ptr2
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr4.cast_mut();
                            }
                        };
                        ptr2
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_read_file<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => {
                                let l1 = *arg0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l2 = *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l1, l2, 1);
                            }
                            _ => {
                                let l3 = *arg0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l4 = *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l3, l4, 1);
                            }
                        }
                    }
                }
                pub trait Guest {
                    #[allow(async_fn_in_trait)]
                    fn add(a: f64, b: f64) -> f64;
                    #[allow(async_fn_in_trait)]
                    fn fibonacci(n: u32) -> u64;
                    #[allow(async_fn_in_trait)]
                    fn greet(name: _rt::String) -> _rt::String;
                    #[allow(async_fn_in_trait)]
                    fn read_file(
                        path: _rt::String,
                    ) -> ::core::result::Result<_rt::String, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_houetor_calc_calc_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "houetor:calc/calc@0.1.0#add")] unsafe extern "C" fn
                        export_add(arg0 : f64, arg1 : f64,) -> f64 { unsafe {
                        $($path_to_types)*:: _export_add_cabi::<$ty > (arg0, arg1) } }
                        #[unsafe (export_name = "houetor:calc/calc@0.1.0#fibonacci")]
                        unsafe extern "C" fn export_fibonacci(arg0 : i32,) -> i64 {
                        unsafe { $($path_to_types)*:: _export_fibonacci_cabi::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "houetor:calc/calc@0.1.0#greet")] unsafe extern "C" fn
                        export_greet(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe
                        { $($path_to_types)*:: _export_greet_cabi::<$ty > (arg0, arg1) }
                        } #[unsafe (export_name =
                        "cabi_post_houetor:calc/calc@0.1.0#greet")] unsafe extern "C" fn
                        _post_return_greet(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_greet::<$ty > (arg0) } }
                        #[unsafe (export_name = "houetor:calc/calc@0.1.0#read-file")]
                        unsafe extern "C" fn export_read_file(arg0 : * mut u8, arg1 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_read_file_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name = "cabi_post_houetor:calc/calc@0.1.0#read-file")]
                        unsafe extern "C" fn _post_return_read_file(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_read_file::<$ty >
                        (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_houetor_calc_calc_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 3 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 3
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, unused_imports, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen::rt::run_ctors_once();
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            unsafe { String::from_utf8_unchecked(bytes) }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        unsafe {
            let layout = alloc::Layout::from_size_align_unchecked(size, align);
            alloc::dealloc(ptr, layout);
        }
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::houetor::calc::calc::__export_houetor_calc_calc_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::houetor::calc::calc);
    };
}
#[doc(inline)]
pub(crate) use __export_plugin_impl as export;
#[rustfmt::skip]
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.62.0:houetor:calc@0.1.0:plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 285] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa0\x01\x01A\x02\x01\
A\x02\x01B\x09\x01@\x02\x01au\x01bu\0u\x04\0\x03add\x01\0\x01@\x01\x01ny\0w\x04\0\
\x09fibonacci\x01\x01\x01@\x01\x04names\0s\x04\0\x05greet\x01\x02\x01j\x01s\x01s\
\x01@\x01\x04paths\0\x03\x04\0\x09read-file\x01\x04\x04\0\x17houetor:calc/calc@0\
.1.0\x05\0\x04\0\x19houetor:calc/plugin@0.1.0\x04\0\x0b\x0c\x01\0\x06plugin\x03\0\
\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.259.0\x10wit-bi\
ndgen-rust\x060.62.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen::rt::maybe_link_cabi_realloc();
}
