// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
// Options used:
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod houetor {
        pub mod spinhog {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod guard {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_spin_cabi<T_: Guest>() {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        { T_::spin() };
                    }
                }
                pub trait Guest {
                    /// Boucle infinie volontaire : plugin malveillant de démonstration (Exp 020).
                    #[allow(async_fn_in_trait)]
                    fn spin() -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_houetor_spinhog_guard_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "houetor:spinhog/guard@0.1.0#spin")] unsafe extern "C" fn
                        export_spin() { unsafe { $($path_to_types)*::
                        _export_spin_cabi::<$ty > () } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_houetor_spinhog_guard_0_1_0_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, unused_imports, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen::rt::run_ctors_once();
    }
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::houetor::spinhog::guard::__export_houetor_spinhog_guard_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::houetor::spinhog::guard);
    };
}
#[doc(inline)]
pub(crate) use __export_plugin_impl as export;
#[rustfmt::skip]
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.62.0:houetor:spinhog@0.1.0:plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 212] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07X\x01A\x02\x01A\x02\x01\
B\x02\x01@\0\x01\0\x04\0\x04spin\x01\0\x04\0\x1bhouetor:spinhog/guard@0.1.0\x05\0\
\x04\0\x1chouetor:spinhog/plugin@0.1.0\x04\0\x0b\x0c\x01\0\x06plugin\x03\0\0\0G\x09\
producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.259.0\x10wit-bindgen-rus\
t\x060.62.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen::rt::maybe_link_cabi_realloc();
}
